wordCount:
      words:
        skip:
        - 'the'
        - 'an'
        - 'a'
      caseSensitive: false
      pattern: "[\\p{Punct}\\s]+"

movie:
      url: "http://www.omdbapi.com"
      apikey: "ed6b8b87"